name: Build Electron App

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build"
        required: true
      source:
        description: "Source to build"
        required: true
      destdir:
        description: "Artifact destination"
        required: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: x64
          - os: macos-latest
            arch: arm64

          # - os: windows-latest
          #   arch: x64
          # - os: windows-latest
          #   arch: ia32
          # - os: windows-latest
          #   arch: arm64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SOURCE_SSK_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan codeup.aliyun.com >> ~/.ssh/known_hosts

      - name: Clone Codeup Repo
        run: |
          git clone ${{ github.event.inputs.source }} app-source
          cd app-source

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          cd app-source 
          npm install
          node build.mjs --arch=${{ matrix.arch }}

      - name: Upload Artifact (for debug)
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}-${{ matrix.arch }}
          path: app-source/${{github.event.inputs.destdir}}/*

      # - name: Upload to Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: release/*.zip
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.MY_ACCESS_TOKEN_TO_GH }}