name: Build Walis App

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build"
        required: true
      source:
        description: "Source to build"
        required: true

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup SSH
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SOURCE_SSK_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan codeup.aliyun.com >> ~/.ssh/known_hosts

      - name: Clone Codeup Repo
        shell: bash
        run: |
          git clone ${{ github.event.inputs.source }} app-source
          cd app-source

      - uses: actions/setup-go@v6
        with:
          go-version-file: 'app-source/go.mod'

      - name: Install Wails
        working-directory: ./app-source
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
        shell: bash

      - name: Install Nsis
        if: ${{ runner.os == 'Windows' }}
        run: winget install NSIS.NSIS --silent

      - name: Install macOS Wails deps
        if: ${{ runner.os == 'macOS' }}
        run: brew install mitchellh/gon/gon
        shell: bash

      - name: Build App
        shell: cmd
        if: ${{ runner.os == 'Windows' }}
        working-directory: ./app-source
        run: build.bat

      - name: Build App
        shell: bash
        if: ${{ runner.os == 'macOS' }}
        working-directory: ./app-source
        run: ./build.sh

      - name: Upload to Release
        uses: softprops/action-gh-release@v3
        with:
          files: app-source/build/bin/*
          name: ${{ github.event.inputs.version }}
          tag_name: ${{ github.event.inputs.version }}
          repository: 
        env:
          GITHUB_TOKEN: ${{ secrets.MY_ACCESS_TOKEN_TO_GH }}