name: Build Walis App

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build"
        required: true
      source:
        description: "Source to build"
        required: true

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: amd64
          - os: macos-latest
            arch: arm64
          - os: windows-latest
            arch: x64
          - os: windows-latest
            arch: ia32

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup SSH
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SOURCE_SSK_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan codeup.aliyun.com >> ~/.ssh/known_hosts

      - name: Clone Codeup Repo
        shell: bash
        run: |
          git clone ${{ github.event.inputs.source }} app-source
          cd app-source

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          app-working-directory: app-source
          go-version: '1.20'

      - name: Clone Codeup Repo
        shell: bash
        run: |
          cd app-source
          if [ -f "post.sh" ]; then
            ./post.sh
          else
            echo "No post.sh found"
          fi
          

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: app-source/build/bin/*
          name: ${{ github.event.inputs.version }}
          tag_name: ${{ github.event.inputs.version }}
          repository: 
        env:
          GITHUB_TOKEN: ${{ secrets.MY_ACCESS_TOKEN_TO_GH }}